// Syncs contract ABIs (and the deployment address) from Foundry's
// artifacts into src/generated/contracts.ts.
//
// Run automatically before `npm run dev` / `npm run build` (pre* scripts),
// or manually with `npm run sync-abi`.
//
// Requires `forge build` to have run. Which deployment is picked up follows
// `VITE_CHAIN`:
//   VITE_CHAIN=sepolia → broadcast/.../11155111/run-latest.json (default chain when hosted)
//   anything else      → broadcast/.../31337/run-latest.json (local Anvil)
// Override any time with the VITE_FACTORY_ADDRESS env var.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const scriptDir = path.dirname(fileURLToPath(import.meta.url))
const frontendDir = path.resolve(scriptDir, '..')
const repoDir = path.resolve(frontendDir, '..')

const outDir = path.join(repoDir, 'out')
const generatedDir = path.join(frontendDir, 'src', 'generated')
const generatedFile = path.join(generatedDir, 'contracts.ts')

const broadcastDir = path.join(repoDir, 'broadcast', 'DeployEscrowFactory.s.sol')

const wantedChainId = (process.env.VITE_CHAIN ?? '').toLowerCase() === 'sepolia' ? '11155111' : '31337'
// strictly the wanted chain — a mismatched address is worse than none
const broadcastFile = path.join(broadcastDir, wantedChainId, 'run-latest.json')
const hasBroadcast = existsSync(broadcastFile)

/** @returns {any[] | null} */
function readAbi(solFile, contractName) {
  const artifact = path.join(outDir, solFile, `${contractName}.json`)
  if (!existsSync(artifact)) return null
  try {
    return JSON.parse(readFileSync(artifact, 'utf8')).abi ?? null
  } catch {
    return null
  }
}

function readDeployedFactory() {
  if (!hasBroadcast) return null
  try {
    const run = JSON.parse(readFileSync(broadcastFile, 'utf8'))
    const tx = (run.transactions ?? []).find(
      (t) => t.transactionType === 'CREATE' && t.contractName === 'EscrowFactory',
    )
    const addr = tx?.contractAddress
    return typeof addr === 'string' && /^0x[0-9a-fA-F]{40}$/.test(addr) ? addr : null
  } catch {
    return null
  }
}

const escrowAbi = readAbi('escrow.sol', 'Escrow')
const factoryAbi = readAbi('EscrowFactory.sol', 'EscrowFactory')

if ((!escrowAbi || !factoryAbi) && !existsSync(generatedFile)) {
  console.error('✖ Foundry artifacts not found. Run `forge build` in the repo root first.')
  process.exit(1)
}

if (!escrowAbi || !factoryAbi) {
  console.warn('⚠ Foundry artifacts missing (run `forge build`); keeping existing generated contracts.')
  process.exit(0)
}

const factoryAddress = readDeployedFactory()

const banner = [
  '// Auto-generated by `npm run sync-abi` — do not edit by hand.',
  '// Run `forge build` (and the deploy script) first.',
  '',
].join('\n')

const contents =
  banner +
  `export const escrowAbi = ${JSON.stringify(escrowAbi, null, 2)} as const\n\n` +
  `export const escrowFactoryAbi = ${JSON.stringify(factoryAbi, null, 2)} as const\n\n` +
  `export const deployedFactoryAddress: \`0x\${string}\` | null = ${
    factoryAddress ? JSON.stringify(factoryAddress) : 'null'
  }\n`

mkdirSync(generatedDir, { recursive: true })
writeFileSync(generatedFile, contents)

console.log(`✔ ABIs synced to src/generated/contracts.ts (chain ${wantedChainId})`)
console.log(
  factoryAddress
    ? `  factory: ${factoryAddress}`
    : `  factory: not deployed on chain ${wantedChainId} yet (run the deploy script, then sync-abi again)`,
)
